### ISSUE TITLE
不知道进度如何？

### ISSUE THREAD

**Issue by YCF** [Lotlab/nrf51822-keyboard#1]
我手上已经在用一个网友做的一个，也是用 nrf51822。

**Comment by jim-kirisame** [comment]
已经完成，虽然还有点小问题就是了

**Comment by YCF** [comment]
要不进群一起讨论？已经正在卖pcb了。

**Comment by jim-kirisame** [comment]
哪个群呢？

**Comment by YCF** [comment]
https://www.v2ex.com/t/348155

**Comment by YCF** [comment]
你可以买板子，然后用自己的程序。。。

**Comment by jim-kirisame** [comment]
我这个其实是设计给G84-4100改装用的，自己的店里也在卖改装套件。暂时对60%的无线键盘无感~
