### ISSUE TITLE
RGB LED per key support

### ISSUE THREAD

**Issue by SinanAkkoyun** [Lotlab/nrf51822-keyboard#12]
Hello, is the RGB implementation for only one LED at the moment?

Would a per key RGB implementation work?

**Comment by jim-kirisame** [comment]
Hi, this project only use LED as status notification (Capslock etc.) and did not contains any RGB LED related code. Maybe you are referring [Lotlab/nrf52-keyboard](https://github.com/Lotlab/nrf52-keyboard) project?

**Comment by SinanAkkoyun** [comment]
Hello, oh I see... II want to build my own flavor of a 60% PCB with RGB support and BLE low power consumption.
I can not read chinese, could you please help me out with which PCB to start?

**Comment by jim-kirisame** [comment]
The PCB project is [here](https://github.com/Lotlab/Lot60-BLE-Keyboard), and the firmware for this pcb is [here](https://github.com/Lotlab/nrf52-keyboard). RGB per key in this firmware is not impliment yet, you may have to write it by yourself.

**Comment by SinanAkkoyun** [comment]
So is there no PCB with RGB support right now?

So the best way to implement RGB underglow support with multiple zones is by using individually addressable RGB LEDs, powering them with a separate LDO and implement them on my own?

Thank you very much

**Comment by SinanAkkoyun** [comment]
And is this based on the GH60? Thx

**Comment by jim-kirisame** [comment]
Yes. Currently there is no PCB with RGB support yet. The keyboard is designing with low power comsumption and RGB LED comsume too many power.

Yes, it's based on GH60.

**Comment by SinanAkkoyun** [comment]
Thanks!

Is the nrf52 more power hungry?
I am sorry for spamming questions :)

**Comment by jim-kirisame** [comment]
Seens there is no significant consumption difference between nrf51 and nrf52

**Comment by SinanAkkoyun** [comment]
I see, do you know the average battery run time for a specific mAh rating for this? 
Last question I swear! :)

**Comment by jim-kirisame** [comment]
~250ua in nrf52

**Comment by SinanAkkoyun** [comment]
So thats the average?????

**Comment by jim-kirisame** [comment]
yes, with all led off and bluetooth connected

**Comment by SinanAkkoyun** [comment]
Wow, thats awesome!!!

Okay really last question, only the NRF chips have to be flashed, the CH554T USB chip works out of the box without any flashing, right?

Thank you so much you helped me out a ton!

**Comment by jim-kirisame** [comment]
CH554T is needed too, you could flash it via usb port so dont worry about it.

**Comment by SinanAkkoyun** [comment]
Okay, thank you!!!
