### ISSUE TITLE
softdevice 选项下编译不通过

### ISSUE THREAD

**Issue by isharrrry** [Lotlab/nrf51822-keyboard#4]
*** Using Compiler 'V5.06 update 5 (build 528)', folder: 'C:\Keil_v5\ARM\ARMCC\Bin'
compiling keymap_storage.c...
..\..\keyboard\keymap_storage.c(2): error:  #5: cannot open source input file "keymap.h": No such file or directory
  #include "keymap.h"
..\..\keyboard\keymap_storage.c: 0 warnings, 1 error
"..\..\keyboard\keymap_storage.c" - 1 Error(s), 0 Warning(s).

**Comment by jim-kirisame** [comment]
Softdevice并不是用于编译的，而是便于烧写SoftDevice而设置的。我会找个时候把它的编译选项给禁用掉的。

**Comment by isharrrry** [comment]
你好，
根据https://blog.csdn.net/dengcanjun6/article/details/54956798
意思就是这个工程SoftDevice包含在main编译出的hex里了吗？
还有就是在BLE4100选项编译时是否默认为
https://wiki.lotlab.org/page/ble4100/advanced/
所示配列？
另外没有看到关于CH554的使用原理图，是否KeymapDownloader需要CH554配合才能完成配列下载？

谢谢

**Comment by isharrrry** [comment]
> Softdevice并不是用于编译的，而是便于烧写SoftDevice而设置的。我会找个时候把它的编译选项给禁用掉的。

你好，
根据https://blog.csdn.net/dengcanjun6/article/details/54956798
意思就是这个工程SoftDevice包含在main编译出的hex里了吗？
还有就是在BLE4100选项编译时是否默认为
https://wiki.lotlab.org/page/ble4100/advanced/
所示配列？
另外没有看到关于CH554的使用原理图，是否KeymapDownloader需要CH554配合才能完成配列下载？

谢谢

**Comment by jim-kirisame** [comment]
> 意思就是这个工程SoftDevice包含在main编译出的hex里了吗？

并不是。nrf51822的烧录需要有三部分的东西：Softdevice、Bootloader和主程序。这三个东西是分开烧录的，而SoftDevice这个选项就是为了方便在IDE里面烧录而设置的。切换到这个选项后，点击IDE上的下载就能直接烧录SoftDevice了。

SoftDevice实际存在的位置是sdk/s110_nrf51_8.0.0_softdevice.hex

> 还有就是在BLE4100选项编译时是否默认为所示配列？

是没错的，BLE4100选项的默认IO配置是那个wiki里面所示的配置。

> 另外没有看到关于CH554的使用原理图，是否KeymapDownloader需要CH554配合才能完成配列下载？

对，那个是留给BLE60的。BLE60可以先看看[原理图](https://github.com/Lotlab/nrf51822-keyboard/files/2705816/keyboard.pdf)，工程我会找个时间传上来。

**Comment by isharrrry** [comment]
> > 意思就是这个工程SoftDevice包含在main编译出的hex里了吗？
> 
> 并不是。nrf51822的烧录需要有三部分的东西：Softdevice、Bootloader和主程序。这三个东西是分开烧录的，而SoftDevice这个选项就是为了方便在IDE里面烧录而设置的。切换到这个选项后，点击IDE上的下载就能直接烧录SoftDevice了。
> 
> SoftDevice实际存在的位置是sdk/s110_nrf51_8.0.0_softdevice.hex
> 
> > 还有就是在BLE4100选项编译时是否默认为所示配列？
> 
> 是没错的，BLE4100选项的默认IO配置是那个wiki里面所示的配置。
> 
> > 另外没有看到关于CH554的使用原理图，是否KeymapDownloader需要CH554配合才能完成配列下载？
> 
> 对，那个是留给BLE60的。BLE60可以先看看[原理图](https://github.com/Lotlab/nrf51822-keyboard/files/2705816/keyboard.pdf)，工程我会找个时间传上来。

编译并用nrfgo依次烧写sd dfu app后，上电没有搜到蓝牙，esc键（短接p0.28 p0.21）触发时上电也不能搜到dfu的蓝牙信号，然后看工程里时nrf51422，我的是nrf51822AA芯片，工程是不是还需要从新配置成nrf51822AA的iram等信息

**Comment by jim-kirisame** [comment]
应该是不用的？
你可以尝试把KEYBOARD_DEBUG打开，在main.c里面，去掉开机时候的[按键检测](https://github.com/Lotlab/nrf51822-keyboard/blob/9ccda83f3b5e3f801f2263920ba39658091f481b/main/ble/main.c#L270)
